################################################################################
#
# Default avocadocs settings
#
# All settings can be overwritten in your Params, either individually, or by
#   specifying a new `docstyle` parameter that has a matching file at
#   data/yourdocstyle.yaml|json|toml. You can use this file as a reference for
#   both approaches.
#
################################################################################

# Basics
version: "v0.0.1"
description: Platform.sh User Documentation
author: Platform.sh
title: User documentation
issuerepo: "https://github.com/platformsh/platformsh-docs/"
repo: "https://github.com/platformsh/platformsh-docs/"
editPageButton: true

# Images (kept in static/)
logo: "images/logos/Platformsh_logo_white.svg"
logolinksto: "https://platform.sh"
favicon: "images/logos/favicon.ico"

# Search
searchtext: "Type to search"
searchIndex:
  base: /

# 404
_404:
  title: "Lost in space"
  image: "/images/404-8.png"
  issues: "https://github.com/platformsh/platformsh-docs/issues/new"

# Books
# Note: If you would like sections to match uglyurls, add the ".html" extension manually to `section`.
#     (i.e. books.example.section: example.html)
books:
  home:
    title: User Documentation
    section: "/"
    weight: -120
  example:
    title: Getting Started
    section: gettingstarted.html
    weight: -110

# Fonts
# font:
  # main:
    # font: "Overpass"
    # family-sans-serif: "'Overpass', sans-serif;"
    # font: "Oxygen"
    # source: "remote"
  # mono:
    # font: "Overpass+Mono"
    # font: "Oxygen+Mono"
    # family-monospace: "'Overpass Mono', monospace;"
    # source: "remote"

# Colors
colors:
  palette:
    night: "1A182A"
    ebony: "302F45"
    slate: "5F5E7O"
    granite: "98A0AB"
    stone: "E7E7E7"
    snow: "FFFFFF"
    blue: "145CC6"
    orange: "FB3728"
    pink: "FFBDBB"
    light-pink: "FFEEEEE"
  brand:
    brand-color-primary-blue: "#145CC6"
    brand-color-light-blue: "#d0def4"
    brand-font-color-black: "#49475F"
    brand-font-color-dark: "#3E3D54"
    sidebar-bg-color: "#EDEDEF"
    sidebar-bg-logo : "#1A182A"
    button-bg-blue: "#145CC6"
    button-bg-pink: "#FFBDBB"
    button-bg-gold: "#DD901A"
    top-bg-color: "#302F45"
  brand-callouts:
    primary: "#E7E7E7"
    secondary: "#6e1ac9"
    success: "#00c9a7"
    info: "#00dffc"
    warning: "#ffc107"
    danger: "#de4437"
    light: "#f8fafd"
    dark: "#1e2022"
    primary-lighter: "#1e2022"
    dark-soft: "#7e8892"
  # hamburger: "#145CC6"
  standard:
    blue: "#007bff"
    indigo: "#6610f2"
    purple: "#6f42c1"
    pink: "#e83e8c"
    red: "#dc3545"
    orange: "#fd7e14"
    yellow: "#ffc107"
    green: "#28a745"
    teal: "#20c997"
    cyan: "#17a2b8"
    white: "#fff"
    gray: "#8c98a4"
    gray-dark: "#343a40"
    black: "#000"
    black-soft: "rgba(0, 0, 0, 0.22)"

# Metadata
meta:
  sitename: "Platform.sh User Documentation"
  description: Platform.sh is a second-generation Platform-as-a-Service built especially for continuous deployment. It allows you to host web applications on the cloud while making your development and testing workflows more productive.
  image: "images/avocadocs/Platformsh_icon_black.svg"
  url: "https://docs.platform.sh"
  twittercard:
    card: "product"
    site: "@platformsh"
    title: "Platform.sh User Documentation"
    description: "Platform.sh is a second-generation Platform-as-a-Service built especially for continuous deployment. It allows you to host web applications on the cloud while making your development and testing workflows more productive."
    creator: "@platformsh"
    image: "images/avocadocs/Platformsh_icon_black.svg"
  keywords:
    - PaaS
    - cloud hosting
    - DevOps
    - PHP
    - Node.js
    - Go
    - Golang
    - Python
    - .NET
    - Ruby
    - Java
    - Drupal
    - Wordpress
    - Symfony
    - Maven
    - Lisp
    - Hibernate
    - Jakarta
    - Spring
    - TYPO3
