# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: php

# The toolstack used to build the application.
type: php:7.0
build:
    flavor: composer

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            root: "_books"
            passthru: "/index.php"
            index:
                - "index.html"
            expires: -1
            scripts: true
            allow: false
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html?)$:
                    allow: true
                ^/robots\.txt$:
                    allow: true
                search_index\.json$:
                    allow: true
# The size of the persistent disk of the application (in MB).
disk: 2048

# Build time dependencies.
dependencies:
  nodejs:
    gitbook-cli: "*"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      ./build_all
