name: 'search'

type: 'python:3.8'

variables:
    env:
        MEILISEARCH_VERSION: 'v0.15.0'
        POETRY_VERSION: '1.1.4'
        POETRY_VIRTUALENVS_IN_PROJECT: true
        POETRY_VIRTUALENVS_CREATE: false

# relationships:
#     docs: "docs:http"

hooks:
    build: !include
        type: string
        path: build.sh
    deploy: !include
        type: string
        path: deploy.sh
    post_deploy: !include
        type: string
        path: post_deploy.sh

web:
    commands:
      # Run the Meilisearch server
      start: "./meilisearch --http-addr localhost:${PORT} --master-key $PLATFORM_PROJECT_ENTROPY"

# The size of the persistent disk of the application (in MB).
disk: 2048

mounts:
    "data.ms":
        source: local
        source_path: "datams"
    "output":
        source: local
        source_path: "output"
    "config":
        source: local
        source_path: config
