---
buildDraft: true
buildFuture: true
buildExpired: true
enableRobotsTXT: true

disableKinds:
  - taxonomy
  - "404"
  - RSS
  - taxonomyTerm
  - sitemap

outputs:
  home:
    - JSON
  page:
    - JSON
  section:
    - JSON

imaging:
  quality: 50

paginate: 50000
paginatePath: list
publishDir: indexing

ignoreFiles:
  - "\\.png$"
  - "\\.jpg$"
  - "\\.jpeg$"
