https://{default}/:
  type: upstream
  upstream: docs:http
  cache:
    enabled: true
  ssi:
    enabled: false
  redirects:
    paths:
      # Getting Started Restructure June 2019
      "/gettingstarted/tools.html": { "to": "/development/tools.html", "code": 301, "prefix": false}
      "/gettingstarted/cli.html": { "to": "/development/cli.html", "code": 301, "prefix": false}
      "/gettingstarted/cli/api-tokens.html": { "to": "/development/cli/api-tokens.html", "code": 301, "prefix": false}
      "/gettingstarted/local.html": { "to": "/development/local.html", "code": 301, "prefix": false}
      "/gettingstarted/local/tethered.html": { "to": "/development/local/tethered.html", "code": 301, "prefix": false}
      "/gettingstarted/local/untethered.html": { "to": "/development/local/untethered.html", "code": 301, "prefix": false}
      "/gettingstarted/local/lando.html": { "to": "/development/local/lando.html", "code": 301, "prefix": false}
      "/gettingstarted/local/docksal.html": { "to": "/development/local/docksal.html", "code": 301, "prefix": false}
      "/gettingstarted/first-project.html": { "to": "/gettingstarted/template.html", "code": 301, "prefix": false}

      # Renamed in August 2019.
      "/administration/snapshot-and-restore.html": { "to": "/administration/backup-and-restore.html", "code": 301, "prefix": false}

      # Reorganized in May 2020
      "/administration/integrations.html": { "to": "/integrations/overview.html", "code": 301, "prefix": false }
      "/administration/integrations/bitbucket.html": { "to": "/integrations/source/bitbucket.html", "code": 301, "prefix": false }
      "/administration/integrations/blackfire.html": { "to": "/integrations/profiling/blackfire.html", "code": 301, "prefix": false }
      "/administration/integrations/tideways.html": { "to": "/integrations/profiling/tideways.html", "code": 301, "prefix": false }
      "/administration/integrations/notifications.html": { "to": "/integrations/notifications.html", "code": 301, "prefix": false }
      "/administration/integrations/new-relic.html": { "to": "/integrations/profiling/new-relic.html", "code": 301, "prefix": false }
      "/administration/integrations/github.html": { "to": "/integrations/source/github.html", "code": 301, "prefix": false }
      "/administration/integrations/gitlab.html": { "to": "/integrations/source/gitlab.html", "code": 301, "prefix": false }
      "/administration/integrations/hipchat.html": { "to": "/integrations/activity/hipchat.html", "code": 301, "prefix": false }
      "/administration/integrations/webhooks.html": { "to": "/integrations/activity/webhooks.html", "code": 301, "prefix": false }
      "/administration/integrations/activity-scripts.html": { "to": "/integrations/activity.html", "code": 301, "prefix": false }

      # Reorganized August 2020
      "^/gettingstarted/gettingstarted(.*)": { "to": "/gettingstarted/introduction$1", "code": 301, "regexp": true }

      # Reorganized September 2020
      "/golive/steps/dns.html": { "to": "/golive/steps/dns.html", "code": 301, "prefix": false}


"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"https://search.{default}/":
    type: upstream
    upstream: "search:http"
    id: "search"

"https://www.search.{default}/":
    type: redirect
    to: "https://search.{default}/"
