http://www.{default}/:
  type: redirect
  to: https://{default}/
http://{default}/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  upstream: app:http
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: true
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
