
# Basics
baseURL: /
title: avocadocs
author: Platform.sh
description: A Hugo Documentation Theme by Platform.sh

# Themes
theme: avocadocs
# themesdir: ../..

# Language settings
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 10
  # li:
  #   contentDir: content/lorem
  #   languageName: Lorem Ipsum
  #   weight: 20

# Syntax highlighting
markup:
  highlight:
    style: friendly
