################################################################################
#
# Default avocadocs settings
#
# All settings can be overwritten in your Params, either individually, or by
#   specifying a new `docstyle` parameter that has a matching file at
#   data/yourdocstyle.yaml|json|toml. You can use this file as a reference for
#   both approaches.
#
################################################################################

# Basics
version: "v0.0.1"
description: A Hugo Documentation Theme by Platform.sh
author: Platform.sh
title: User documentation
issuerepo: "https://github.com/platformsh/platformsh-docs/"
repo: "https://github.com/platformsh/platformsh-docs/"
editPageButton: true

# Images (kept in static/)
# showVersionBadge: true
logo: "images/avocadocs/avocadocs-light.svg"
# logolinksto: "https://platform.sh"
favicon: "images/avocadocs/avocado-icon-dark.png"

# Welcome message
welcome:
  dop:
    template: "https://raw.githubusercontent.com/platformsh/template-builder/master/templates/hugo/.platform.template.yaml"
    utm_content: "hugo"
  logo: "images/avocadocs/avocadocs-dark.svg"
  credit: A Hugo Documentation Theme by Platform.sh
  desc: avocadocs is a mobile-first documentation theme for Hugo written and maintained by the Platform.sh Developer Relations team. It relies heavily on the DocsUIKit open-source Bootstrap template made by HTMLStream.



# Search
searchtext: "Type to search"
searchIndex:
  base: /

# 404
_404:
  title: "Lost in space"
  image: "/images/404-8.png"
  issues: "https://github.com/platformsh/platformsh-docs/issues/new"

# Books
# Note: If you would like sections to match uglyurls, add the ".html" extension manually to `section`.
#     (i.e. books.example.section: example.html)
books:
  home:
    title: User Documentation
    section: "/"
    weight: -120
  example:
    title: Basic Example Site
    section: example
    weight: -110
  faq:
    title: FAQ
    section: faq
    weight: -100
  community:
    title: External link
    url: "https://community.platform.sh/"
    weight: -90

# Fonts
font:
  main:
    # font: "Overpass"
    # family-sans-serif: "'Overpass', sans-serif;"
    # font: "Oxygen"
    # source: "remote"
  mono:
    # font: "Overpass+Mono"
    # font: "Oxygen+Mono"
    # family-monospace: "'Overpass Mono', monospace;"
    # source: "remote"

# Colors
colors:
  brand:
    brand-color-primary-blue: "#145CC6"
    brand-color-light-blue: "#d0def4"
    brand-font-color-black: "#49475F"
    brand-font-color-dark: "#3E3D54"
    sidebar-bg-color: "#EDEDEF"
    sidebar-bg-logo : "#1A182A"
    button-bg-blue: "#145CC6"
    button-bg-pink: "#FFBDBB"
    button-bg-gold: "#DD901A"
    top-bg-color: "#302F45"
  brand-callouts:
    primary: "#107ef4"
    secondary: "#6e1ac9"
    success: "#00c9a7"
    info: "#00dffc"
    warning: "#ffc107"
    danger: "#de4437"
    light: "#f8fafd"
    dark: "#1e2022"
    primary-lighter: "#1e2022"
    dark-soft: "#7e8892"
  # hamburger: "#145CC6"
  standard:
    blue: "#007bff"
    indigo: "#6610f2"
    purple: "#6f42c1"
    pink: "#e83e8c"
    red: "#dc3545"
    orange: "#fd7e14"
    yellow: "#ffc107"
    green: "#28a745"
    teal: "#20c997"
    cyan: "#17a2b8"
    white: "#fff"
    gray: "#8c98a4"
    gray-dark: "#343a40"
    black: "#000"
    black-soft: "rgba(0, 0, 0, 0.22)"

# Footer
footer:
  # Copyright
  # copyright:
  #   year: 2020
  #   name: "Platform.sh"
  #   url: "https://platform.sh"
  #   license: "MIT LICENSE"
  # Icon attribution
  icon-attr: true
  # links
  links:
    - name: "Theme"
      url: "https://platform.sh"
    - name: "Changelog"
      url: "https://platform.sh"
    - name: "License"
      url: "https://platform.sh"
    - name: "Contributing"
      url: "https://platform.sh"
    - name: "Platform.sh"
      url: "https://platform.sh"
    - name: "Hugo"
      url: "https://platform.sh"
  # Social
  social:
    github: "https://github.com/platformsh"
    facebook: "https://facebook.com/platform.sh"
    # instagram: "none"
    twitter: "https://twitter.com/platformsh"
    # dribble: "none"

# Metadata
meta:
  sitename: "avocadocs"
  description: avocadocs is a mobile-first documentation theme for Hugo written and maintained by the Platform.sh Developer Relations team.
  image: "images/avocadocs/avocado-icon-dark.png"
  url: "https://htmlstream.com/preview/docs-ui-kit/index.html"
  twittercard:
    card: "product"
    site: "@platformsh"
    title: "avocadocs: A Hugo Documentation Theme by Platform.sh"
    description: "avocadocs is a mobile-first documentation theme for Hugo written and maintained by the Platform.sh Developer Relations team."
    creator: "@platformsh"
    image: "images/avocadocs/avocado-icon-dark.png"
  keywords:
    - documentation
    - template
    - open source
    - hugo
