# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'docs'

# The type key specifies the language and version for your application.
type: 'nodejs:14'

# Specify the Hugo version as an env variable.
variables:
    env:
        HUGOVERSION: 0.78.0

relationships:
    search: "search:http"

# The hooks that will be triggered when the package is deployed.
hooks:
    build: !include
      type: string
      path: build.sh
    deploy: !include
      type: string
      path: deploy.sh
    post_deploy: !include
      type: string
      path: post_deploy.sh

# The configuration of the application when it is exposed to the web.
web:
    commands:
      # Run a no-op process that uses no CPU resources, since this is a static site.
      start: sleep infinity
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'public'
            passthru: false
            index: ['index.html']
            scripts: false
            allow: true
            expires: 24h
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                    expires: 4w

disk: 1024

mounts:
  "public/scripts/xss/dist/config":
      source: service
      service: files
      source_path: config

