name = "avocadocs"
license = "MIT"
licenselink = "https://github.com/platformsh/avocadocs/blob/master/LICENSE.md"
description = "avocadocs is a mobile-first documentation theme for Hugo written and maintained by the Platform.sh Developer Relations team. It relies heavily on the DocsUIKit open-source Bootstrap templates made by HTMLStream."
min_version = "0.66.0"
tags = [
  "documentation"
        ]

[author]
  name = "Platform.sh"
  homepage = "https://platform.sh"

# If porting an existing theme
# [original]
#   name = "academic"
#   homepage = "https://sourcethemes.com/academic/"
#   repo = "https://github.com/gcushen/hugo-academic"
