# Enable Varnish, by pointing to the 'varnish' service. This will map all
# incoming requests to the Varnish service rather than the application.
# Varnish will then, based on the VCL file defined in 'services.yaml',
# forward requests to the application as appropriate.
"https://{default}/":
    type: upstream
    upstream: "varnish:http"
    # Disable the router cache as it is now entirely redundant with Varnish.
    cache:
        enabled: false